spring.application.name=tutorias

spring.config.import=optional:file:.env[.properties]

server.port=${PORT:8080}

api.key=${API_KEY}
api.jwt.expiration=${API_JWT_EXPIRATION}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:true}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_STARTTLS:true}
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SSL:false}
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
