spring.application.name=tutorias


api.key=JohnBaeHyunKangSeulgiSonSeungwangParkSoohyunKimYerim

spring.datasource.url=jdbc:postgresql://localhost:5432/tutorias
spring.datasource.username=postgres
spring.datasource.password=postgres